### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by jfischoff** [spacebudz/app#2]
Without a LICENSE the file is implicitly all rights reserved. This is fine; however, an explicit license would most likely limit liability if anyone uses the code and loses money.  That is my understanding, but I am not a lawyer. 

I think having an explicit license would just make it clear if the authors meant to release it, all rights reserved or not.

**Comment by alessandrokonrad** [comment]
Thank you! Yes, that makese sense of course. Will add a LICENSE.
