### ISSUE TITLE
Differences between serialization libs?

### ISSUE THREAD

**Issue by stephenhuh** [spacebudz/app#4]
Hey there!

Thank you for everything you're doing for the ADA community!

I've noticed that there are some differences between the imported `cardano-serialization-library` and the one inside the `custom_modules` folder. Do you mind explaining why there were local modifications to the lib? Notably, the `set_plutus_data` function on `TransactionBuilder` and some of the `LanguageViews` functionality are in this repo, but not in emurgos.

@jfischoff

**Comment by blockchainUni** [comment]
What exactly is LanguageViews used for ? and how do we use it ?
